// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiLab3.Models;

#nullable disable

namespace WebApiLab3.Migrations
{
    [DbContext(typeof(ItiContext))]
    [Migration("20260418133648_AddIdentityTablesFix")]
    partial class AddIdentityTablesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.Course", b =>
                {
                    b.Property<int>("CrsId")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Id");

                    b.Property<int?>("CrsDuration")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Duration");

                    b.Property<string>("CrsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Crs_Name");

                    b.Property<int?>("TopId")
                        .HasColumnType("int")
                        .HasColumnName("Top_Id");

                    b.HasKey("CrsId");

                    b.HasIndex("TopId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Id");

                    b.Property<string>("DeptDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Dept_Desc");

                    b.Property<string>("DeptLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dept_Location");

                    b.Property<int?>("DeptManager")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Manager");

                    b.Property<string>("DeptName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dept_Name");

                    b.Property<DateOnly?>("ManagerHiredate")
                        .HasColumnType("date")
                        .HasColumnName("Manager_hiredate");

                    b.HasKey("DeptId");

                    b.HasIndex("DeptManager");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.InsCourse", b =>
                {
                    b.Property<int>("InsId")
                        .HasColumnType("int")
                        .HasColumnName("Ins_Id");

                    b.Property<int>("CrsId")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Id");

                    b.Property<string>("Evaluation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InsId", "CrsId");

                    b.HasIndex("CrsId");

                    b.ToTable("Ins_Course", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.Instructor", b =>
                {
                    b.Property<int>("InsId")
                        .HasColumnType("int")
                        .HasColumnName("Ins_Id");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Id");

                    b.Property<string>("InsDegree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ins_Degree");

                    b.Property<string>("InsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ins_Name");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.HasKey("InsId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.StudCourse", b =>
                {
                    b.Property<int>("CrsId")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Id");

                    b.Property<int>("StId")
                        .HasColumnType("int")
                        .HasColumnName("St_Id");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.HasKey("CrsId", "StId");

                    b.HasIndex("StId");

                    b.ToTable("Stud_Course", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.Student", b =>
                {
                    b.Property<int>("StId")
                        .HasColumnType("int")
                        .HasColumnName("St_Id");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Id");

                    b.Property<string>("StAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("St_Address");

                    b.Property<int?>("StAge")
                        .HasColumnType("int")
                        .HasColumnName("St_Age");

                    b.Property<string>("StFname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("St_Fname");

                    b.Property<string>("StLname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("St_Lname")
                        .IsFixedLength();

                    b.Property<int?>("StSuper")
                        .HasColumnType("int")
                        .HasColumnName("St_super");

                    b.HasKey("StId");

                    b.HasIndex("DeptId");

                    b.HasIndex("StSuper");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("WebApiLab3.Models.Topic", b =>
                {
                    b.Property<int>("TopId")
                        .HasColumnType("int")
                        .HasColumnName("Top_Id");

                    b.Property<string>("TopName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Top_Name");

                    b.HasKey("TopId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiLab3.Models.Course", b =>
                {
                    b.HasOne("WebApiLab3.Models.Topic", "Top")
                        .WithMany("Courses")
                        .HasForeignKey("TopId")
                        .HasConstraintName("FK_Course_Topic");

                    b.Navigation("Top");
                });

            modelBuilder.Entity("WebApiLab3.Models.Department", b =>
                {
                    b.HasOne("WebApiLab3.Models.Instructor", "DeptManagerNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("DeptManager")
                        .HasConstraintName("FK_Department_Instructor");

                    b.Navigation("DeptManagerNavigation");
                });

            modelBuilder.Entity("WebApiLab3.Models.InsCourse", b =>
                {
                    b.HasOne("WebApiLab3.Models.Course", "Crs")
                        .WithMany("InsCourses")
                        .HasForeignKey("CrsId")
                        .IsRequired()
                        .HasConstraintName("FK_Ins_Course_Course");

                    b.HasOne("WebApiLab3.Models.Instructor", "Ins")
                        .WithMany("InsCourses")
                        .HasForeignKey("InsId")
                        .IsRequired()
                        .HasConstraintName("FK_Ins_Course_Instructor");

                    b.Navigation("Crs");

                    b.Navigation("Ins");
                });

            modelBuilder.Entity("WebApiLab3.Models.Instructor", b =>
                {
                    b.HasOne("WebApiLab3.Models.Department", "Dept")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_Instructor_Department");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("WebApiLab3.Models.StudCourse", b =>
                {
                    b.HasOne("WebApiLab3.Models.Course", "Crs")
                        .WithMany("StudCourses")
                        .HasForeignKey("CrsId")
                        .IsRequired()
                        .HasConstraintName("FK_Stud_Course_Course");

                    b.HasOne("WebApiLab3.Models.Student", "St")
                        .WithMany("StudCourses")
                        .HasForeignKey("StId")
                        .IsRequired()
                        .HasConstraintName("FK_Stud_Course_Student");

                    b.Navigation("Crs");

                    b.Navigation("St");
                });

            modelBuilder.Entity("WebApiLab3.Models.Student", b =>
                {
                    b.HasOne("WebApiLab3.Models.Department", "Dept")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_Student_Department");

                    b.HasOne("WebApiLab3.Models.Student", "StSuperNavigation")
                        .WithMany("InverseStSuperNavigation")
                        .HasForeignKey("StSuper")
                        .HasConstraintName("FK_Student_Student");

                    b.Navigation("Dept");

                    b.Navigation("StSuperNavigation");
                });

            modelBuilder.Entity("WebApiLab3.Models.Course", b =>
                {
                    b.Navigation("InsCourses");

                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("WebApiLab3.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("WebApiLab3.Models.Instructor", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("InsCourses");
                });

            modelBuilder.Entity("WebApiLab3.Models.Student", b =>
                {
                    b.Navigation("InverseStSuperNavigation");

                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("WebApiLab3.Models.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
